  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Update to your Python version

      - name: Set up environment variables from secrets
        run: |
          echo "export MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> $GITHUB_ENV
          echo "export MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
          echo "export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "export MYSQL_DB=${{ secrets.MYSQL_DB }}" >> $GITHUB_ENV
          echo "export SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      - name: Load environment variables
        run: source $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'justorder'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_532E6012C484414C9A4432C7B0F30ED1 }}
